# -*- coding: utf-8 -*-
"""Tool python Youtube - by soiqualang.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E4B0xMXFpcX13gpPTx4scNP_hRulNxPG
"""

#autosub
# !sudo add-apt-repository ppa:mc3man/trusty-media
#!sudo apt-get update
# !sudo apt-get install ffmpeg -y
# !sudo pip install autosub

#Download youtube
# !pip install pytube

#youtube 2 mp3
# !pip install youtube_dl

import os
from pathlib import Path
import subprocess
import requests
# from __future__ import unicode_literals
import youtube_dl
import argparse


"""#Download video

https://github.com/soiqualang/youtube-dl#format-selection
"""

def youtube2video(download_path,youtube_url):
    Location = '%s soiqualang_%(extractor)s-%(id)s-%(title)s.%(ext)s'.replace("%s ", download_path)
    ytdl_format_options = {
        'outtmpl': Location
    }
    with youtube_dl.YoutubeDL(ytdl_format_options) as ydl:
         ydl.download([youtube_url])

# youtube2video('concoc/','http://www.youtube.com/watch?v=BaW_jenozKc')

"""#Download mp3"""

def youtube2mp3(download_path,youtube_url):
    Location = '%s soiqualang_%(extractor)s-%(id)s-%(title)s.%(ext)s'.replace("%s ", download_path)
    ydl_opts = {
        'outtmpl': Location,
        'format': 'bestaudio/best',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
    }
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download([youtube_url])

# youtube2mp3('concoc/','http://www.youtube.com/watch?v=BaW_jenozKc')

"""#Get all video in youtube list"""

def get_listvideo(download_path,youtube_url):    
    cmd='youtube-dl -o "'+download_path+'/%(uploader)s/%(playlist_uploader)s/%(playlist_index)s - %(title)s.%(ext)s" '+youtube_url
    # print(cmd)
    subprocess.Popen(cmd,shell=True)


def run_tyoutube(download_mode,download_path,youtube_url):
    finalchar=download_path[len(download_path)-1]
    if(finalchar!='/'):
        download_path+='/'

    if(download_mode=='video'):
        youtube2video(download_path,youtube_url)
    elif(download_mode=='mp3'):
        youtube2mp3(download_path,youtube_url)
    elif(download_mode=='list'):
        get_listvideo(download_path,youtube_url)
    elif(download_mode=='transcript'):
        print('Đang xây dựng :v')
    else:
        youtube2video(download_path,youtube_url)


def arg_parsing_v2(params):
    parser = argparse.ArgumentParser(description='ArgumentParser by soiqualang')
    for param in params:
        param='-'+str(param)
        parser.add_argument(param, required=True,
                            help='Input parammeter')
    args = parser.parse_args()
    args = vars(args)
    return args


params=['download_mode','youtube_url','download_path']
ARGS = arg_parsing_v2(params)

download_mode=ARGS['download_mode']
youtube_url=ARGS['youtube_url']
download_path=ARGS['download_path']

run_tyoutube(download_mode,download_path,youtube_url)


# List video
# python tyb.py -download_mode "list" -youtube_url "PLhPvsstp6O2QTcrY20ysXRbyRo30am87X" -download_path "keochanh_mp3"
# python tyb.py -download_mode "list" -youtube_url "https://www.youtube.com/playlist?list=PLhPvsstp6O2QTcrY20ysXRbyRo30am87X" -download_path "keochanh_mp3"

# a video
# python tyb.py -download_mode "video" -youtube_url "https://www.youtube.com/watch?v=tNfGBssfCmE" -download_path "keochanh_mp3"

# a mp3
# python tyb.py -download_mode "mp3" -youtube_url "https://www.youtube.com/watch?v=tNfGBssfCmE" -download_path "keochanh_mp3"