# -*- coding: utf-8 -*-
"""Tool python Youtube - by soiqualang.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E4B0xMXFpcX13gpPTx4scNP_hRulNxPG
"""

#autosub
# !sudo add-apt-repository ppa:mc3man/trusty-media
#!sudo apt-get update
# !sudo apt-get install ffmpeg -y
# !sudo pip install autosub

#Download youtube
# !pip install pytube

#youtube 2 mp3
# !pip install youtube_dl

import os
from pathlib import Path
import subprocess
import requests
# from __future__ import unicode_literals
import youtube_dl


"""#Download video

https://github.com/soiqualang/youtube-dl#format-selection
"""

def youtube2video(download_path,youtube_url):
    Location = '%s soiqualang_%(extractor)s-%(id)s-%(title)s.%(ext)s'.replace("%s ", download_path)
    ytdl_format_options = {
        'outtmpl': Location
    }
    with youtube_dl.YoutubeDL(ytdl_format_options) as ydl:
         ydl.download([youtube_url])

# youtube2video('concoc/','http://www.youtube.com/watch?v=BaW_jenozKc')

"""#Download mp3"""

def youtube2mp3(download_path,youtube_url):
    Location = '%s soiqualang_%(extractor)s-%(id)s-%(title)s.%(ext)s'.replace("%s ", download_path)
    ydl_opts = {
        'outtmpl': Location,
        'format': 'bestaudio/best',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
    }
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download([youtube_url])

# youtube2mp3('concoc/','http://www.youtube.com/watch?v=BaW_jenozKc')

"""#Get all video in youtube list"""

def get_listvideo(youtube_url):
    # !youtube-dl -o '%(uploader)s/%(playlist_uploader)s/%(playlist_index)s - %(title)s.%(ext)s' https://www.youtube.com/watch?v=_cWJOTA7-MA&list=PL88783CDDEBA66859
    
    cmd='youtube-dl -o "%(uploader)s/%(playlist_uploader)s/%(playlist_index)s - %(title)s.%(ext)s" '+youtube_url
    # print(cmd)
    subprocess.Popen(cmd,shell=True)


def run_tyoutube(func_selected,download_path,youtube_url):
    finalchar=download_path[len(download_path)-1]
    if(finalchar!='/'):
        download_path+='/'

    if(func_selected=='Download video'):
        youtube2video(download_path,youtube_url)
    elif(func_selected=='Download mp3'):
        youtube2mp3(download_path,youtube_url)
    elif(func_selected=='Get all video in list'):
        get_listvideo(youtube_url)
    elif(func_selected=='Video to text'):
        print('Đang xây dựng :v')
    else:
        youtube2video(download_path,youtube_url)



""" func_selected = "Download mp3" #@param ["Download video", "Download mp3", "Get all video in list", "Video to text"]
youtube_url = 'https://www.youtube.com/watch?v=tNfGBssfCmE'  #@param {type: "string"}
download_path = 'keochanh_mp3'  #@param {type: "string"}

run_tyoutube(func_selected,download_path,youtube_url) """


func_selected = "Get all video in list" #@param ["Download video", "Download mp3", "Get all video in list", "Video to text"]
youtube_url = 'https://www.youtube.com/playlist?list=PLhPvsstp6O2QTcrY20ysXRbyRo30am87X'  #@param {type: "string"}
download_path = 'keochanh_mp3'  #@param {type: "string"}

run_tyoutube(func_selected,download_path,youtube_url)